### ISSUE TITLE
List item indention are strange 

### ISSUE THREAD

**Issue by liubin** [k0kubun/md2key#1]
List item from the second, with additional two spaces added.

The source
```
# Test

- item1
- item2
- item3

```

The generated keynote slide:
![screen shot 2015-08-07 at 2 53 41 pm](https://cloud.githubusercontent.com/assets/1212008/9130502/f1711026-3d15-11e5-8c8c-740fb198f6ef.png)

Workaround, change https://github.com/k0kubun/md2key/blob/master/lib/md2key/keynote.rb#L41 to 
```
set object text of default body item to "  #{content}"
```
By adding two spaces before real content.

Thanks,
Bin

**Comment by k0kubun** [comment]
Thank you for reporting an issue!

The problem was that the code md2key generates includes a real newline.

```applescript
tell application "Keynote"
            tell document 1
              set newSlide to make new slide

              tell newSlide
                set object text of default title item to "Title"
                set object text of default body item to "item1
  item2
  item3"
              end tell
            end tell
end tell
```

I changed it to:


```applescript
tell application "Keynote"
            tell document 1
              set newSlide to make new slide

              tell newSlide
                set object text of default title item to "Title"
                set object text of default body item to "item1\nitem2\nitem3"
              end tell
            end tell
end tell
```
