### ISSUE TITLE
" and $ should be escaped

### ISSUE THREAD

**Issue by liubin** [k0kubun/md2key#16]
If the string contains " or $ , the behaviour will be strange.

**Comment by k0kubun** [comment]
Resolved in md2key v0.5.1.

## input
```md
# "foo $bar "baz

- "foo $bar "baz
```

## output
![2016-04-23 17 14 27](https://cloud.githubusercontent.com/assets/3138447/14760154/e2d7cb58-0976-11e6-8b4e-e97a1c19c4f7.png)
