### ISSUE TITLE
Not compatible with Keynote 6.6.1?

### ISSUE THREAD

**Issue by liubin** [k0kubun/md2key#22]
I' using Keynote 6.6.1 and md2key 0.4.4, and will got these errors:

```
every slide of document 1 doesn’t understand the “count” message
```
or

```
slide 2 of document 1 doesn’t understand the “move” message
```

**Comment by k0kubun** [comment]
I tested Keynote 6.6.1 and md2key just now but it worked fine.
Maybe some contents in your markdown contain characters which can't be processed by md2key 0.4.4.

Could you try reducing your decks and detecting what kind of code breaks md2key?

**Comment by k0kubun** [comment]
I guess this issue is related to https://github.com/k0kubun/md2key/issues/16 and it may be resolved.
So closing for now but feel free to reopen this if the issue consists in md2key v0.5.1.

**Comment by liubin** [comment]
Ok, after I do some edit of my markdown file, it now worked.

I don't know the extract reason, but now it worked. :-)
