### ISSUE TITLE
uninitialized constant Redcarpet::Render::XHTML (NameError)

### ISSUE THREAD

**Issue by Adagio-cantabile** [k0kubun/md2key#38]
Hey, there. I was following the instructions in readme file, but I got an error message saying `uninitialized constant Redcarpet::Render::XHTML (NameError)` when I run `md2key markdown.md` from terminal.
I'm using ruby 2.2.3 and redcarpet-3.4.0, here is the backtrace:
```
/Users/user/.rvm/gems/ruby-2.2.3/gems/md2key-0.8.1/lib/md2key/parser.rb:121:in `to_xhtml': uninitialized constant Redcarpet::Render::XHTML (NameError)
	from /Users/user/.rvm/gems/ruby-2.2.3/gems/md2key-0.8.1/lib/md2key/parser.rb:24:in `parse_slides'
	from /Users/user/.rvm/gems/ruby-2.2.3/gems/md2key-0.8.1/lib/md2key/parser.rb:13:in `parse'
	from /Users/user/.rvm/gems/ruby-2.2.3/gems/md2key-0.8.1/lib/md2key/cli.rb:14:in `convert'
	from /Users/user/.rvm/gems/ruby-2.2.3/gems/md2key-0.8.1/lib/md2key/cli.rb:32:in `method_missing'
	from /Users/user/.rvm/gems/ruby-2.2.3/gems/thor-0.19.4/lib/thor/command.rb:29:in `run'
	from /Users/user/.rvm/gems/ruby-2.2.3/gems/thor-0.19.4/lib/thor/command.rb:126:in `run'
	from /Users/user/.rvm/gems/ruby-2.2.3/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/user/.rvm/gems/ruby-2.2.3/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/user/.rvm/gems/ruby-2.2.3/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/user/.rvm/gems/ruby-2.2.3/gems/md2key-0.8.1/exe/md2key:6:in `<top (required)>'
	from /Users/user/.rvm/gems/ruby-2.2.3/bin/md2key:23:in `load'
	from /Users/user/.rvm/gems/ruby-2.2.3/bin/md2key:23:in `<main>'
	from /Users/user/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/user/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

The strange thing is in irb, I did
```
2.2.3 :001 > require 'redcarpet'
 => true
2.2.3 :002 > Redcarpet::Render::XHTML
 => Redcarpet::Render::XHTML
```
and it works fine, what do you think about it?

**Comment by k0kubun** [comment]
I'm not sure because I can't reproduce your error. I'll try following things if I could reproduce your environment:

- disabling rvm and try system ruby
- for the case redcarpet.so is broken, `gem uninstall --force redcarpet && gem install redcarpet` and retry `md2key`
- clone md2key repository and try `bundle exec exe/md2key`
- check `gem list` to find unexpected gem including redcarpet.rb
- I would add `binding.pry` directly to md2key/parser.rb and check `$LOAD_PATH` during execution. Which load path has redcarpet.rb first?
- give up all things and reinstall ruby 2.2.3

**Comment by Adagio-cantabile** [comment]
Happy new year's day! 良いお年を
Thank you for your reply, I changed the version of redcarpet from 3.4.0 to 3.3.4 and it works. I noticed 3.4.0 was released several days ago, maybe something was broken there, have you checked the compatibility with this new version ?

**Comment by k0kubun** [comment]
Happy new year!

I tested md2key with redcarpet 3.4.0 but it worked. It seems that difference between 3.4.0 and 3.3.4 isn't important and new installation is actually important. While I don't know how you switched from 3.4.0 to 3.3.4, I guess installing 3.4.0 after uninstalling 3.4.0 may let it work.

**Comment by Adagio-cantabile** [comment]
Yeah, I reinstalled redcarpet 3.4.0 and it works, seems it wasn't properly installed before. Thanks !
