### ISSUE TITLE
Bug: Not generating the correct slides

### ISSUE THREAD

**Issue by ferreiro** [k0kubun/md2key#40]
Hello again,
I've just created a simple template with 2 slides:
- Master. Which contains logo + title + subtitle
- Title+Body.

When using your script with the test sample, the placeholder texts are not well substituted, generating an undesired presentation. This is the result:

<img width="1045" alt="screen shot 2017-05-22 at 2 20 40 am" src="https://cloud.githubusercontent.com/assets/7242959/26288565/4b477216-3e95-11e7-98a0-a7397243ad76.png">

<img width="1044" alt="screen shot 2017-05-22 at 2 20 47 am" src="https://cloud.githubusercontent.com/assets/7242959/26288566/4b4a20ba-3e95-11e7-9a61-1eb8d2412afb.png">

The template.key and test.md are attached to the issue in this zip:

[Presentation.zip](https://github.com/k0kubun/md2key/files/1017482/Presentation.zip)

Is there a problem in the way templates declare the placeholders or there is a problem with the library itself? How to fix this?

**Comment by k0kubun** [comment]
Did you follow usage https://github.com/k0kubun/md2key#usage? md2key expects at least 2 master slides to be used in your base presentation.

**Comment by k0kubun** [comment]
Ah, sorry, I'm checking your slides now. Please forget my previous comment.

**Comment by k0kubun** [comment]
It looks like you don't prepared 2nd page as master slide. To let md2key recognize the textarea to put texts, you should prepare master slides correctly. At least "Title" and "Body" MUST be checked in your right side.

Please do "Edit Master Slide" and create one properly.

**Comment by ferreiro** [comment]
Ah! Okey! Thank you man.

I think including this information as a note in the Readme would be extremely helpful so future clients will not forget to mark both options.

Also, we can include the following image to make things easy to configure for newbies.
<img width="332" alt="screen shot 2017-05-22 at 2 38 47 am" src="https://cloud.githubusercontent.com/assets/7242959/26288704/e5d3855c-3e97-11e7-8e41-a11cdb55acdf.png">

What do you think? If agree, I can update the Readme and create a new PR

**Comment by k0kubun** [comment]
Agreed.
