### ISSUE TITLE
Can’t get document 1. Invalid index. (-1719)

### ISSUE THREAD

**Issue by joao-parana** [k0kubun/md2key#45]
What is going wrong with my simple example.

```bash
md2key  default.md 
```

I'm getting this error:

```text
72:131: execution error: Keynote got an error: Can’t get document 1. Invalid index. (-1719)
```

My file `default.md` is this

```markdown
# The presentation
@k0kubun

## Hello world
- I'm takashi kokubun
- This is a pen
  - Nested item is available

## How are you?
- I'm fine thank you

```

And my presentation is a copy off assets/default.key

Tanks in advance.

**Comment by k0kubun** [comment]
Do you open document while executing md2key like in README.md? https://github.com/k0kubun/md2key#usage

**Comment by joao-parana** [comment]
Ok, its works now with the document opened on Keynote Application. Tanks
