### ISSUE TITLE
ERROR:  While executing gem ... (Gem::FilePermissionError)

### ISSUE THREAD

**Issue by SagarPrajapati98** [k0kubun/md2key#51]
i am not able to install this package 
Mac : 10.15
Xcode : 11.3

can you please let me know how to install this i am new to apple script

**Comment by k0kubun** [comment]
Please put entire command output of `sudo gem install md2key`

**Comment by SagarPrajapati98** [comment]
Building native extensions. This could take a while...
ERROR:  Error installing md2key:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.6.0/gems/redcarpet-3.5.0/ext/redcarpet
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20200903-2879-1chcasu.rb extconf.rb
creating Makefile

current directory: /Library/Ruby/Gems/2.6.0/gems/redcarpet-3.5.0/ext/redcarpet
make "DESTDIR=" clean

current directory: /Library/Ruby/Gems/2.6.0/gems/redcarpet-3.5.0/ext/redcarpet
make "DESTDIR="
make: *** No rule to make target `"/Applications/Xcode', needed by `autolink.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in /Library/Ruby/Gems/2.6.0/gems/redcarpet-3.5.0 for inspection.
Results logged to /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-19/2.6.0/redcarpet-3.5.0/gem_make.out

**Comment by SagarPrajapati98** [comment]
@k0kubun this what it show when i tried sudo for install package

**Comment by k0kubun** [comment]
hmmm interesting. I bet `sudo gem install redcarpet` would also fail and that's the problem you're facing. Could you get help from https://github.com/vmg/redcarpet about `sudo gem install redcarpet` failure first?

**Comment by SagarPrajapati98** [comment]
@k0kubun thanks let me check with redcarpet really appreciate

**Comment by swnwtep** [comment]
I think I have fixed this problem with the redcarpet MakeFile which is looking for:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin19/ruby/config.h'
This is now in universal-darwin**20**/ruby/config.h
I made a symlink universal-darwin19 -> universal-darwin20 and the redcarpet and the other GEMs compile

**Comment by k0kubun** [comment]
Thanks. Since it's about another gem and there's nothing to fix in this repository, let me close this issue.

**Comment by swnwtep** [comment]
Hi Takashi

Thanks for letting me know 
I didn’t understand the code well enough to find the fault - seems to be something to do with the GEM MakeFile picking up a XCode ruby config.h rather than from the system ruby
Useful to have my “fix” online somewhere for anyone else with the same problem

regards
David
