### ISSUE TITLE
[Feature Request] Speaker notes

### ISSUE THREAD

**Issue by tddschn** [k0kubun/md2key#53]
Thank you so much for making this awesome tool! 

md2key reduces most of my manual work when creating slides, but I wish I could automate the creation of speaker notes too. Would you consider adding this feature?

**Comment by amatsuda** [comment]
@tddschn It's already implemented via #28, in the following notation:
```md
## Title
body

^ notes
```

**Comment by tddschn** [comment]
Thank you!
