### ISSUE TITLE
Nested list

### ISSUE THREAD

**Issue by k0kubun** [k0kubun/md2key#6]
Code like following example is parsed correctly but wrongly rendered to keynote (flattened).

```markdown
- foo
  - bar
- hello
```

I think we can do this with applescript by clicking default body of a slide and input cursor key or indentation bindings.

**Comment by tooh** [comment]
+1

**Comment by matthias-vogt** [comment]
+1

**Comment by kennyz** [comment]
good idea!

**Comment by k0kubun** [comment]
This is supported in md2key v0.5.0. 💎
