### ISSUE TITLE
Automatic bootstrap

### ISSUE THREAD

**Issue by k0kubun** [k0kubun/md2key#7]
I want to generate keynote even if keynote is not activated.

``` bash
# List up keynote themes
$ md2key themes
theme1
theme2
...

# Craete keynote from selected theme
$ md2key create markdown.md -t theme1
```

I think we can do this using https://github.com/katsuma/keynote-client. I'm waiting it to be pushed to rubygems.

**Comment by katsuma** [comment]
Thank you for your interest :smile: 
Now I pushed current alpha version as v0.0.1.
- https://rubygems.org/gems/keynote-client

This gem will help you to use any themes.
You can get all themes like this.

```ruby
theme_names = Keynote::Theme.find_by(:all).map(&:name)
```

**Comment by k0kubun** [comment]
Thank you for pushing a nice gem to rubygems! :+1:

**Comment by k0kubun** [comment]
This problem seems to be solved already. Closing :pray:
